### ISSUE TITLE
shaka.player.js version 

### ISSUE THREAD

**Issue by bandirsen** [AriasBros/flutter_video_player_web_shaka#2]
I couldn't find information about shaka.player.js version used in this project, or this compatible with all shaka player version ?

**Comment by AriasBros** [comment]
Hi @bandirsen 

The version used is the 4.1.0. You can see it here: https://github.com/AriasBros/flutter_video_player_web_shaka/blob/main/lib/src/shaka_video_player.dart#L18

For now this is hardcoded.

**Comment by bandirsen** [comment]
Thank for the information. 
I will close this
